// examples/react/src/slots/AnswerBadge.tsx
/**
 * 편집기 캔버스의 커스텀 객체 — **미리보기**다.
 *
 * 편집은 인스펙터에서 한다 (PLAN D26). 캔버스에서 입력을 받으려 하면 드래그와 포커스가 같은
 * 포인터 이벤트를 다투게 되고, `pointerdown` 의 `preventDefault()` 가 포커스를 취소한다.
 */
import type { CustomSlotProps } from 'pdf-canvas-kit/react'
import type { Answer } from '../objectType'

export function AnswerBadge({ data }: CustomSlotProps<Answer>) {
  const filled = data.answers.some((a) => a.trim())
  return (
    <div className="ex-badge">
      <b>{data.points}점</b>
      {!filled && <span className="ex-badge-warn">정답 미입력</span>}
    </div>
  )
}

// examples/vue/src/AnswerBadge.vue
<script setup lang="ts">
// 편집기 캔버스 — 미리보기. 편집은 인스펙터에서 한다 (PLAN D26).
import type { Answer } from './objectType'

const props = defineProps<{ objectId: string; data: Answer }>()
const filled = () => props.data.answers.some((a) => a.trim())
</script>

<template>
  <div style="padding: 0 8px; font-size: 11px; line-height: 44px">
    <b>{{ data.points }}점</b>
    <span v-if="!filled()" style="color: #b4342b; margin-left: 6px">정답 미입력</span>
  </div>
</template>
